
# Snakemake general parameters

jobs: 999
use-conda: True
conda-frontend: conda


# Snakemake cluster parameters
immediate-submit: True  # a modifier si je nai pas de checkpoint(et ajouter --immediate-submit dans slurmsubmit.py)
rerun-triggers: mtime
cluster: '../profile_slurm/slurmSubmit.py {dependencies}' # script for sbatch jobs
cluster-config: '../profile_slurm/cluster.yaml' # config parameters for each rule
notemp: True
keep-going: True
